se muestra un mensaje cuando se va a preparar el router

diff --git a/bin/internet-etecsa-login b/bin/internet-etecsa-login
--- a/bin/internet-etecsa-login
+++ b/bin/internet-etecsa-login
@@ -7,6 +7,8 @@
 
 
 # precondiciones para conectarse a internet
+
+## alistar router de ser necesario
 prepare_m5_dhcp() {
   local -r AUTH_NODE='secure.etecsa.net'
   local -r AIROS_DEVICE_IP='192.168.0.1'
@@ -19,10 +21,11 @@ prepare_m5_dhcp() {
 
   # si el portal está disponible no se hace nada y se sale
   timeout 2 ping -c 1 $AUTH_NODE &> /dev/null && { 
-    echo 'OK'
+    echo 'Router listo'
     return 0
   }
 
+  notify-send "Preparando router..."
   # de no estar disponible el portal se renova la ip WAN del dispositivo AirOS, se imprime un mensaje y se sale
   # sshpass -p $AIROS_PASSWORD ssh "ubnt@$AIROS_DEVICE_IP" -- "udhcpc -f -q -n -i ath0 -s /etc/udhcpc/udhcpc renew" > /dev/null 2>&1 && {
   ssh -o 'ConnectTimeout=2' \
@@ -31,12 +34,12 @@ prepare_m5_dhcp() {
       -o 'StrictHostKeyChecking=no' \
       "ubnt@$AIROS_DEVICE_IP" -- \
       "udhcpc -f -q -n -i ath0 -s /etc/udhcpc/udhcpc renew" > /dev/null 2>&1 && {
-    echo "Renovada la ip del Router"
+    echo "Router listo, ip renovada"
     return 0
   }
 
   # de no poderse renovar la ip WAN del dispositivo AirOS se imprime un mensaje y se sale
-  echo "ERROR: No se pudo renovar la ip del Router" 1>&2
+  echo "ERROR: No se pudo renovar la ip del router" 1>&2
   return 1
 }
 
@@ -48,7 +51,7 @@ msg="$(prepare_m5_dhcp 2>&1)" || code=$?
 if [ "$code" = 0 ]; then
   curl 'http://localhost:4500/toggle'
 else
-   notify-send "msg: ${msg}"
+   notify-send "${msg}"
 fi
 
 
