implementado update

diff --git a/update b/update
--- a/update
+++ b/update
@@ -11,10 +11,39 @@ set -o nounset
 # set -o xtrace
 ##
 
+readonly LOG_FILE='/var/log/internet-etecsa-login.log'
+readonly GIT_PACKAGE_URL='http://gitea.casa.dylgran.com/yuniel/internet-etecsa-login/raw/branch/master/package.json'
+
+log() {
+  local -r code="$1"
+  local -r msg="$2"
+  echo "$(date +%Y%m%d-%H%M%S)  [UPDATE]  ${code} ${msg}" >> "$LOG_FILE"
+}
+# hay internet?
+timeout 2 ping -c 1 8.8.8.8 &> /dev/null || {
+  log 1 'ERROR: No hay internet, no se ha podido actualizar'
+  exit 1
+}
+
 cd '/opt/internet-etecsa-login'
+readonly cur_version="$(jq '.version' './package.json')"
+readonly git_version="$(wget -qO - "$GIT_PACKAGE_URL" | jq '.version')"
+# tenemos la versión mas reciente?
+if [[ "$cur_version" = "$git_version" ]]; then
+  log 0 "No es necesario actualizar, la versión actual ${cur_version} es la más reciente"
+  exit 0
+fi
+# actualizamos
 git pull origin master
 npm install --production --unsafe-perm=true
 # npm update --unsafe-perm=true
-echo 'OK'
-echo '>Ejecute:'
-echo '$ sudo systemctl restart internet-etecsa-login'
+log 0 "Se ha actualizado de ${cur_version} a ${git_version}"
+# se reinicia el servicio solo si el usario no tiene una sesión abierta
+# FIX: tomar puerto de config
+msg="$(curl --silent --show-error 'http://localhost:4500/session-open' 2>&1)"
+if [[ "$msg" != 'true' ]]; then
+  systemctl restart internet-etecsa-login
+  log 0 'Se ha reiniciado el servicio'
+else
+  log 0 'No se ha reiniciado el servicio porque hay una sesión abierta'
+fi
